[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fundbase = "9w9yDjvbLWpv6Cy8g9bXXpxwuJgj4CYtsyMTcHeuMveo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/misbah/.config/solana/id.json"  # ✅ Full absolute path

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
